import Head from "next/head";
import styles from "../styles/Home.module.scss";
import fonts from "../styles/Fonts.module.scss";
import { motion, useMotionValue, useTransform } from "framer-motion";
import { useState } from "react";

export default function Home() {
  const [move, setMove] = useState<boolean>(false);

  const [isOn, setIsOn] = useState<boolean>(false);

  const toggleSwitch = () => setIsOn(!isOn);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.h1
          animate={{ y: [-100, 0], opacity: [0, 1] }}
          className={fonts.title}
        >
          Framer Motion Demo
        </motion.h1>
        <motion.div
          animate={{ y: [100, 0], opacity: [0, 1] }}
          className={styles.content}
        >
          <div className={styles.grid2Cols}>
            <p className={fonts.sectionTitle}>Hover</p>
            <motion.div
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              className={styles.square}
            ></motion.div>
          </div>

          <div className={styles.grid2Cols}>
            <p className={fonts.sectionTitle}>Focus</p>
            <motion.input
              whileFocus={{ boxShadow: "0 0 0 0.4rem rgba(131, 58, 180, 1)" }}
              className={styles.input}
            ></motion.input>
          </div>

          <div className={styles.grid2Cols}>
            <p className={fonts.sectionTitle}>Drag </p>
            <motion.div
              drag
              dragConstraints={{ left: -20, right: 20, top: -10, bottom: 10 }}
              className={styles.square}
            ></motion.div>
          </div>

          <div className={styles.grid2Cols}>
            <p className={fonts.sectionTitle}>Toggle Switch </p>
            <div
              onClick={toggleSwitch}
              data-isOn={isOn}
              className={styles.switchContainer}
            >
              <motion.div layout className={styles.switch}></motion.div>
            </div>
          </div>
        </motion.div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
